name: TVM Windows Build and Release

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*' # タグがプッシュされたときにリリースを作成
  pull_request:
    branches: [ main, master ]
permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - name: カレントディレクトリの確認
        run: pwd

      - name: CMakeの存在確認
        run: cmake --version

      - name: Windows用の長いパス名を有効化
        if: runner.os == 'Windows'
        run: git config --global core.longpaths true

      - name: ccacheのインストール
        run: |
          choco install ccache

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: ディスクの空き容量を表示
        run: Get-PSDrive -PSProvider FileSystem | Select-Object Name, @{Name="Used(GB)";Expression={[math]::round($_.Used/1GB,2)}}, @{Name="Free(GB)";Expression={[math]::round($_.Free/1GB,2)}}, @{Name="Total(GB)";Expression={[math]::round($_.Used/1GB + $_.Free/1GB,2)}}

      # - name: Pythonの依存関係をインストール
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install setuptools wheel numpy

      # - name: Install LLVM
      #  uses: ./.github/actions/setup-llvm-dev
      #  id: setup-llvm
      #  with:
      #      llvm-version: "20.1.0"

      - name: libtvmのソースコードをダウンロード
        uses: actions/checkout@v4
        with:
          repository: apache/tvm
          ref: v0.19.0
          submodules: recursive

      - name: libtvmを設定
        run: |
          mkdir build
          cd build
          cmake .. `
            -G "Visual Studio 16 2019" `
            -DSUMMARIZE=ON `
            -DUSE_CCACHE=ON `
#            -DUSE_LLVM="D:a/lib/LLVM/bin/llvm-config.exe"

      - name: libtvmをビルド
        run: cmake --build build --config Release --target runtime -- /m

      - name: cmakeの状態確認
        run: |
          ccache --show-stats
          ccacche --zero-stats
