name: TVM Windows Build and Release

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*' # タグがプッシュされたときにリリースを作成
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: カレントディレクトリの確認
        run: pwd

      - name: CMakeの存在確認
        run: cmake --version

      - name: Windows用の長いパス名を有効化
        if: runner.os == 'Windows'
        run: git config --global core.longpaths true

      - name: ccacheのインストール
        run: |
          choco install ccache
          echo "CCACHE_DIR=${{ github.workspace }}/.ccache" >> $env:GITHUB_ENV

      - name: ccacheのキャッシュを復元
        uses: actions/cache@v3
        with:
          path: .ccache
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Pythonの依存関係をインストール
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel numpy

      - name: libtvmのソースコードをダウンロード
        uses: actions/checkout@v4
        with:
          repository: apache/tvm
          ref: v0.19.0
          submodules: recursive

      - name: libtvmを設定
        run: |
          mkdir build
          cd build
          cmake .. `
            -DSUMMARIZE=ON `

      - name: libtvmをビルド
        run: |
          cd build
          cmake --build . --config Release
