name: TVM Windows Build and Release

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*' # タグがプッシュされたときにリリースを作成
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: カレントディレクトリの確認
        run: pwd

      - name: CMakeの存在確認
        run: cmake --version

      - name: Windows用の長いパス名を有効化
        if: runner.os == 'Windows'
        run: git config --global core.longpaths true

      - name: ccacheのインストール
        run: |
          choco install ccache
          echo "CCACHE_DIR=${{ github.workspace }}/.ccache" >> $env:GITHUB_ENV

      - name: ccacheのキャッシュを復元
        uses: actions/cache@v3
        with:
          path: .ccache
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Pythonの依存関係をインストール
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel numpy

      - name: libtvmのソースコードをダウンロード
        uses: actions/checkout@v4
        with:
          repository: apache/tvm
          submodules: recursive

      - name: libtvmをビルド
        run: |
          cd tvm
          mkdir build
          cd build
          cmake .. \
            -DUSE_LLVM=ON \
            -DUSE_CUDA=OFF \
            -DUSE_VULKAN=OFF \
            -DUSE_OPENGL=OFF \
            -DUSE_OPENCL=OFF \
            -DUSE_METAL=OFF \
            -DUSE_ROCM=OFF \
            -DUSE_HEXAGON=OFF \
            -DUSE_RPC=ON \
            -DUSE_MICRO=OFF \
            -DUSE_CPP_RPC=OFF \
            -DUSE_GRAPH_EXECUTOR=ON \
            -DUSE_GRAPH_EXECUTOR_DEBUG=OFF \
            -DUSE_PROFILER=OFF \
            -DUSE_GTEST=OFF \
            -DUSE_LIBBACKTRACE=OFF \
            -DHIDE_PRIVATE_SYMBOLS=ON \
            -DINSTALL_DEV=ON \
            -DUSE_FALLBACK_STL_MAP=ON \
            -DUSE_THREADS=ON \
            -DUSE_RANDOM=ON \
            -DUSE_MICRO_STANDALONE_RUNTIME=OFF \
            -DUSE_BYODT_POSIT=OFF \
            -DUSE_BLAS=none \
            -DUSE_MKL=OFF \
            -DUSE_MKLDNN=OFF \
            -DUSE_DNNL=OFF \
            -DUSE_CUDNN=OFF \
            -DUSE_CUBLAS=OFF \
            -DUSE_THRUST=OFF \
            -DUSE_MIOPEN=OFF \
            -DUSE_ROCBLAS=OFF \
            -DUSE_SORT=ON \
            -DUSE_NNPACK=OFF \
            -DUSE_LIBTORCH=OFF \
            -DUSE_HWLOC=OFF \
            -DUSE_STACKVM=ON \
            -DUSE_RELAY_DEBUG=OFF \
            -DUSE_TENSORRT=OFF \
            -DUSE_VITIS_AI=OFF \
            -DUSE_ANTLR=OFF \
            -DUSE_CMSISNN=OFF \
            -DUSE_ARM_COMPUTE_LIB=OFF \
            -DUSE_TFLITE=OFF \
            -DUSE_TENSORFLOW_PATH=OFF \
            -DUSE_FLATBUFFERS=OFF \
            -DUSE_ETHOSN=OFF \
            -DUSE_CLML=OFF \
            -DUSE_TARGET_ONNX=OFF \
            -DUSE_ARM_DOT=OFF \
            -DUSE_PAPI=OFF \
            -DUSE_VERILATOR=OFF \
            -DUSE_LIBUSB=OFF \
            -DUSE_MICRO_ONLY=OFF \
            -DUSE_ZEPHYR=OFF \
            -DUSE_ARDUINO=OFF \
            -DUSE_MICRO_EXECUTOR=OFF \
            -DUSE_ETHOSU=OFF \
            -DUSE_UNITY=OFF \
            -DUSE_CCACHE=ON \
            -DUSE_SANITIZER=OFF \
            -DUSE_COVERAGE=OFF \
            -DUSE_KALEIDOSCOPE=OFF \
            -DUSE_CUTLASS=OFF \
            -DUSE_XGBOOST=OFF \
            -DUSE_LIGHTGBM=OFF \
            -DUSE_TREELITE=OFF \
            -DUSE_CLANG=OFF \
            -DUSE_MSVC=ON \
            -DUSE_PROFILER_VTUNE=OFF \
            -DUSE_STDCPP=17 \
            -DUSE_OPENMP=ON \
            -DUSE_WEBGPU=OFF \
            -DUSE_WEBGPU_RUNTIME=OFF \
            -DUSE_SPIRV_KHR_INTEGER_DOT_PRODUCT=OFF \
            -DUSE_MYELIN=OFF \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=install \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -DCMAKE_VERBOSE_MAKEFILE=OFF \
            -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
            -DCMAKE_CXX_STANDARD=17 \
            -DCMAKE_CXX_STANDARD_REQUIRED=ON \
            -DCMAKE_CXX_EXTENSIONS=OFF \
            -DCMAKE_C_STANDARD=11 \
            -DCMAKE_C_STANDARD_REQUIRED=ON \
            -DCMAKE_C_EXTENSIONS=OFF \
            -DCMAKE_POLICY_DEFAULT_CMP0091=NEW \
            -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded
          cmake --build . --config Release
