name: TVM Windows Build and Release

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*' # タグがプッシュされたときにリリースを作成
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: 確認
        run: pwd

      - name: CMakeの存在確認
        run: cmake --version
