name: TVM Windows Build and Release

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*' # タグがプッシュされたときにリリースを作成
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: カレントディレクトリの確認
        run: pwd

      - name: CMakeの存在確認
        run: cmake --version

      - name: Windows用の長いパス名を有効化
        if: runner.os == 'Windows'
        run: git config --global core.longpaths true

      - name: libtvmのソースコードをダウンロード
        uses: actions/checkout@v4
        with:
          repository: apache/tvm
          submodules: recursive

      - name: libtvmをビルド
        run: |
          cd tvm
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release
